import type { Course } from "@/types/course.type";

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Lập trình JavaScript cơ bản",
    shortDescription:
      "Học JavaScript từ cơ bản đến nâng cao với các ví dụ thực tế",
    detailedDescription:
      "Khóa học này sẽ giúp bạn nắm vững các kiến thức cơ bản về JavaScript, bao gồm biến, hàm, đối tượng, và các khái niệm lập trình hướng đối tượng. Bạn sẽ được thực hành với nhiều bài tập thực tế.",
    level: "basic",
    thumbnail:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/javascript-programming-T2M5VadSlHoh9kdqvU5E9GUfm3722c.png",
    status: "published",
    tags: ["Lập trình", "JavaScript", "Web Development"],
    teacherId: "teacher1",
    teacherName: "Nguyễn A",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    lessonsCount: 12,
    rating: 4.5,
    reviewCount: 128,
    price: 299000,
    originalPrice: 399000,
  },
  {
    id: "2",
    title: "React.js cho người mới bắt đầu",
    shortDescription: "Xây dựng ứng dụng web hiện đại với React.js",
    detailedDescription:
      "Khóa học React.js từ cơ bản đến nâng cao, bao gồm components, hooks, state management và các best practices trong phát triển ứng dụng React.",
    level: "intermediate",
    thumbnail:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/react-javascript-library-7HGQTGZOLKg1E3oUSHx4JWAtl3vabR.png",
    status: "published",
    tags: ["React", "JavaScript", "Frontend"],
    teacherId: "teacher2",
    teacherName: "kjfndjvn",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-05"),
    lessonsCount: 18,
    rating: 4.5,
    reviewCount: 95,
    price: 499000,
    originalPrice: 699000,
  },
  {
    id: "3",
    title: "Node.js và Express Framework",
    shortDescription: "Phát triển backend với Node.js và Express",
    detailedDescription:
      "Học cách xây dựng API RESTful với Node.js và Express, kết nối database, authentication và deployment.",
    level: "advanced",
    thumbnail:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/nodejs-backend-PwHwnygRN0CUi7FISJdD8kyZphKyY9.png",
    status: "published",
    tags: ["Node.js", "Backend", "API"],
    teacherId: "teacher1",
    teacherName: "Nguyễn A",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-25"),
    lessonsCount: 15,
    rating: 4.2,
    reviewCount: 67,
    price: 599000,
  },
  {
    id: "4",
    title: "Thiết kế UI/UX với Figma",
    shortDescription: "Học thiết kế giao diện người dùng chuyên nghiệp",
    detailedDescription:
      "Khóa học thiết kế UI/UX từ cơ bản đến nâng cao với Figma, bao gồm design system, prototyping và user research.",
    level: "basic",
    thumbnail: "/ui-ux-design-figma.png",
    status: "draft",
    tags: ["UI/UX", "Design", "Figma"],
    teacherId: "teacher3",
    teacherName: "nvnd",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-12"),
    lessonsCount: 10,
    rating: 4.4,
    reviewCount: 43,
    price: 399000,
    originalPrice: 499000,
  },
  {
    id: "5",
    title: "Python cho Data Science",
    shortDescription: "Phân tích dữ liệu với Python và các thư viện phổ biến",
    detailedDescription:
      "Học Python cho Data Science với pandas, numpy, matplotlib và scikit-learn. Thực hành với các dự án phân tích dữ liệu thực tế.",
    level: "intermediate",
    thumbnail: "/placeholder-v0kyb.png",
    status: "published",
    tags: ["Python", "Data Science", "Machine Learning"],
    teacherId: "teacher2",
    teacherName: "dknnv",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-30"),
    lessonsCount: 20,
    rating: 4.0,
    reviewCount: 156,
    price: 799000,
    originalPrice: 999000,
  },
];

export const mockTopics = [
  "Lập trình",
  "JavaScript",
  "React",
  "Node.js",
  "Python",
  "UI/UX",
  "Design",
  "Data Science",
  "Machine Learning",
  "Web Development",
  "Frontend",
  "Backend",
  "API",
  "Figma",
];
