import type { FlashcardData } from "@/types/flashcard";
import { z } from "zod";
import { categoriesService } from "./categories.service";
import type { FileForAI } from "./file-to-ai.service";

const inFlight = new Map<string, Promise<FlashcardAIResponse>>();

// Strong hash key generation using crypto-like approach
function makeRequestKey(
  content: string,
  model: string,
  settings?: any,
): string {
  const raw = JSON.stringify({
    content: content.slice(0, 2000),
    model,
    settings,
    timestamp: Math.floor(Date.now() / 60000), // 1-minute cache window
  });

  // FNV-1a hash with better distribution
  let hash = 2166136261;
  for (let i = 0; i < raw.length; i++) {
    hash ^= raw.charCodeAt(i);
    hash = (hash * 16777619) >>> 0;
  }

  hash ^= content.length;
  hash ^= model.length << 8;

  return `${hash.toString(36)}-${Date.now().toString(36)}`;
}

// Zod schemas for validation
const FlashcardSchema = z.object({
  id: z.union([z.string(), z.number()]).transform(String),
  question: z.string().min(1),
  choices: z.array(z.string()).min(2).max(6),
  correctAnswer: z.number().int().min(0),
  explanation: z.string().default(""),
  difficulty: z.enum(["EASY", "MEDIUM", "HARD"]).default("EASY"),
  tags: z.array(z.string()).default([]),
  sourceFile: z.string().optional(),
  sourceContext: z.string().optional(),
});

const FlashcardAIResponseSchema = z.object({
  title: z.string().default("AI Generated Flashcards"),
  description: z.string().default("Flashcards generated by AI"),
  flashcards: z.array(FlashcardSchema),
  metadata: z
    .object({
      total_cards: z.number(),
      difficulty: z.string(),
      estimated_study_time: z.number(),
      generated_from: z.string(),
      generation_mode: z.string(),
    })
    .optional(),
  selectedCategory: z.string().optional(),
});

// Server-side only constants
const DEFAULT_MODEL = "openai/gpt-4o-mini";

export interface FlashcardAIResponse {
  success: boolean;
  flashcards?: FlashcardData[];
  title?: string;
  description?: string;
  metadata?: any;
  selectedCategory?: string;
  error?: string;
}

// Utility functions for ID generation
export function generateFlashcardId(): string {
  return `fc-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

// Enhanced error handling for server API calls
function handleServerAPIError(error: string): string {
  if (error.includes("fetch")) {
    return "Network error - please check your connection";
  }
  if (error.includes("timeout")) {
    return "Request timeout - please try again";
  }
  if (error.includes("API key")) {
    return "Invalid API key - please check your configuration";
  }
  return error || "Unknown server error";
}

// Server-side API call function
async function callServerAPI(
  endpoint: string,
  payload: any,
  signal?: AbortSignal,
): Promise<any> {
  try {
    const response = await fetch(`/api/ai/${endpoint}`, {
      method: "POST",
      signal,
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorData = await response
        .json()
        .catch(() => ({ error: "Unknown error" }));
      throw new Error(
        handleServerAPIError(
          errorData.error || `Server error: ${response.status}`,
        ),
      );
    }

    return await response.json();
  } catch (error) {
    console.error(`Server API call to ${endpoint} failed:`, error);
    throw error;
  }
}

// Drop-in parsing utility with Zod validation
function parseFlashcardAIResponse(aiResponse: string): {
  flashcards: FlashcardData[];
  title: string;
  description: string;
  metadata?: any;
  selectedCategory?: string;
} {
  // Clean response
  const content = aiResponse
    .trim()
    .replace(/<think>[\s\S]*?<\/think>/gi, "")
    .replace(/```json\s*([\s\S]*?)\s*```/i, "$1")
    .replace(/```\s*([\s\S]*?)\s*```/i, "$1")
    .trim();

  if (process.env.NODE_ENV === "development") {
    console.log("🔍 Parsing Flashcard AI response:", content.substring(0, 500));
  }

  // Try direct JSON parse with Zod validation
  try {
    const parsed = JSON.parse(content);
    const validated = FlashcardAIResponseSchema.safeParse(parsed);

    if (validated.success) {
      const data = validated.data;
      const flashcards = data.flashcards.map((fc, index) => ({
        id: Number(fc.id) || index + 1,
        question: fc.question,
        choices: fc.choices,
        correctAnswer: fc.correctAnswer,
        explanation: fc.explanation,
        difficulty: fc.difficulty,
        tags: fc.tags,
      }));

      console.log(`✅ Zod validation success: ${flashcards.length} flashcards`);
      return {
        flashcards,
        title: data.title,
        description: data.description,
        metadata: data.metadata,
        selectedCategory: data.selectedCategory,
      };
    }
    console.warn("⚠️ Zod validation failed:", validated.error.issues);
  } catch (error) {
    console.warn("⚠️ Direct JSON parse failed:", error);
  }

  // Fallback: try to extract flashcards array
  try {
    const flashcardsMatch = content.match(/"flashcards"\s*:\s*\[([\s\S]*)/i);
    if (flashcardsMatch) {
      const flashcardsContent = `[${flashcardsMatch[1]}`;
      const lastBracket = flashcardsContent.lastIndexOf("]");
      if (lastBracket > 0) {
        const flashcardsArray = flashcardsContent.substring(0, lastBracket + 1);
        const parsed = JSON.parse(flashcardsArray);

        if (Array.isArray(parsed)) {
          const validFlashcards: FlashcardData[] = [];

          for (const fc of parsed) {
            const validated = FlashcardSchema.safeParse(fc);
            if (validated.success) {
              validFlashcards.push({
                id: Number(validated.data.id) || validFlashcards.length + 1,
                question: validated.data.question,
                choices: validated.data.choices,
                correctAnswer: validated.data.correctAnswer,
                explanation: validated.data.explanation,
                // difficulty: validated.data.difficulty,
                // tags: validated.data.tags,
              });
            } else {
              console.warn(
                "⚠️ Invalid flashcard skipped:",
                validated.error.issues,
              );
            }
          }

          if (validFlashcards.length > 0) {
            console.log(
              `✅ Fallback parsing success: ${validFlashcards.length} flashcards`,
            );
            return {
              flashcards: validFlashcards,
              title: "AI Generated Flashcards",
              description: `Generated ${validFlashcards.length} flashcards using AI`,
            };
          }
        }
      }
    }
  } catch (error) {
    console.warn("⚠️ Fallback parsing failed:", error);
  }

  console.error("❌ Failed to parse flashcard AI response");
  return {
    flashcards: [],
    title: "AI Generated Flashcards",
    description: "Failed to generate flashcards",
  };
}

// Generate flashcard title and description using AI
export async function generateFlashcardTitleDescription(params: {
  content: string;
  flashcards: FlashcardData[];
  isExtractMode?: boolean;
  targetLanguage?: string;
  filename?: string;
  category?: string;
  tags?: string[];
  modelName?: string;
}): Promise<{
  success: boolean;
  title?: string;
  description?: string;
  error?: string;
}> {
  const {
    content,
    flashcards,
    isExtractMode,
    targetLanguage = "vi",
    filename,
    category,
    tags,
    modelName = DEFAULT_MODEL,
  } = params;

  try {
    const result = await callServerAPI("generate-flashcard-title-description", {
      content,
      flashcards: flashcards.map((fc) => ({
        question: fc.question,
        choices: fc.choices,
        correctAnswer: fc.correctAnswer,
      })),
      isExtractMode,
      targetLanguage,
      filename,
      category,
      tags,
      modelName,
    });

    if (!result.success || !result.title || !result.description) {
      throw new Error(result.error || "Failed to generate title/description");
    }

    return {
      success: true,
      title: result.title,
      description: result.description,
    };
  } catch (error) {
    console.warn("AI flashcard title/description generation failed:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

// Generate NEW flashcards using AI from content
export async function generateFlashcards(
  params: {
    title: string;
    description: string;
    apiKey: string;
    fileContent?: string;
    modelName?: string;
    settings?: {
      visibility?: string;
      language?: string;
      numberOfCards?: number;
      difficulty?: string;
      generationMode?: "GENERATE" | "EXTRACT";
      fileProcessing?: string;
      parsingMode?: string;
      includeCategories?: boolean;
    };
  },
  signal?: AbortSignal,
): Promise<FlashcardAIResponse> {
  const {
    title,
    description,
    apiKey,
    fileContent = "",
    modelName = DEFAULT_MODEL,
    settings = {},
  } = params;

  const requestKey = makeRequestKey(fileContent, modelName, settings);

  if (inFlight.has(requestKey)) {
    const existingPromise = inFlight.get(requestKey);
    if (existingPromise) {
      return existingPromise;
    }
  }

  const promise = (async (): Promise<FlashcardAIResponse> => {
    try {
      const numberOfCards = Number(settings.numberOfCards) || 5;

      // Get available categories for AI selection if enabled
      let availableCategories = "";
      if (settings.includeCategories !== false) {
        try {
          availableCategories = await categoriesService.getCategoriesForAI();
        } catch (error) {
          console.warn("Failed to fetch categories for AI:", error);
          availableCategories = "No categories available";
        }
      }

      console.log("🚀 Calling generate-flashcards API with payload:", {
        title,
        description,
        apiKey: apiKey ? "***" : "missing",
        fileContent: fileContent ? `${fileContent.length} chars` : "empty",
        modelName,
        settings: { ...settings, numberOfCards },
        availableCategories: availableCategories
          ? `${availableCategories.length} chars`
          : "empty",
      });

      const result = await callServerAPI(
        "generate-flashcards",
        {
          title,
          description,
          apiKey,
          fileContent,
          modelName,
          settings: { ...settings, numberOfCards },
          availableCategories,
        },
        signal,
      );

      if (!result.success) {
        throw new Error(result.error || "Failed to generate flashcards");
      }

      const parsed = parseFlashcardAIResponse(JSON.stringify(result));

      return {
        success: true,
        flashcards: parsed.flashcards,
        title: parsed.title,
        description: parsed.description,
        metadata: parsed.metadata,
        selectedCategory: parsed.selectedCategory,
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    } finally {
      inFlight.delete(requestKey);
    }
  })();

  inFlight.set(requestKey, promise);
  return promise;
}

// Generate flashcards directly from file
export async function generateFlashcardsFromFile(params: {
  title: string;
  description: string;
  apiKey: string;
  modelName?: string;
  settings?: {
    visibility?: string;
    language?: string;
    numberOfCards?: number;
    difficulty?: string;
    generationMode?: "GENERATE" | "EXTRACT";
    fileProcessing?: string;
    parsingMode?: string;
    includeCategories?: boolean;
  };
  file: FileForAI;
}): Promise<FlashcardAIResponse> {
  const {
    title,
    description,
    apiKey,
    modelName = DEFAULT_MODEL,
    settings = {},
    file,
  } = params;

  try {
    const numberOfCards = settings.numberOfCards || "5-10";

    // Get available categories for AI selection if enabled
    let availableCategories = "";
    if (settings.includeCategories !== false) {
      try {
        availableCategories = await categoriesService.getCategoriesForAI();
      } catch (error) {
        console.warn("Failed to fetch categories for AI:", error);
        availableCategories = "No categories available";
      }
    }

    const result = await callServerAPI("generate-flashcards-from-file", {
      title,
      description,
      apiKey,
      modelName,
      settings: { ...settings, numberOfCards },
      file,
      availableCategories,
    });

    if (!result.success) {
      throw new Error(
        result.error || "Failed to generate flashcards from file",
      );
    }

    const parsed = parseFlashcardAIResponse(JSON.stringify(result));

    console.log(
      `✅ Successfully generated ${parsed.flashcards.length} flashcards from file`,
    );
    return {
      success: true,
      flashcards: parsed.flashcards,
      title: parsed.title,
      description: parsed.description,
      metadata: parsed.metadata,
      selectedCategory: parsed.selectedCategory,
    };
  } catch (error) {
    console.error("❌ Flashcard generation from file failed:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

// Extract flashcards using AI (for content that already has flashcard format)
export async function extractFlashcardsWithAI(params: {
  title: string;
  description: string;
  apiKey: string;
  fileContent?: string;
  modelName?: string;
  settings?: {
    visibility?: string;
    language?: string;
    numberOfCards?: number;
    difficulty?: string;
    generationMode?: "GENERATE" | "EXTRACT";
    fileProcessing?: string;
    parsingMode?: string;
    includeCategories?: boolean;
  };
  file?: FileForAI;
}): Promise<FlashcardAIResponse> {
  const {
    title,
    description,
    apiKey,
    fileContent,
    modelName = DEFAULT_MODEL,
    settings = {},
    file,
  } = params;

  try {
    const numberOfCards = settings.numberOfCards || "5-10";

    // Get available categories for AI selection if enabled
    let availableCategories = "";
    if (settings.includeCategories !== false) {
      try {
        availableCategories = await categoriesService.getCategoriesForAI();
      } catch (error) {
        console.warn("Failed to fetch categories for AI:", error);
        availableCategories = "No categories available";
      }
    }

    const result = await callServerAPI("extract-flashcards-ai", {
      title,
      description,
      apiKey,
      fileContent,
      modelName,
      settings: { ...settings, numberOfCards, generationMode: "EXTRACT" },
      file,
      availableCategories,
    });

    if (!result.success) {
      throw new Error(result.error || "Failed to extract flashcards");
    }

    const parsed = parseFlashcardAIResponse(JSON.stringify(result));

    console.log(
      `✅ Successfully extracted ${parsed.flashcards.length} flashcards`,
    );
    return {
      success: true,
      flashcards: parsed.flashcards,
      title: parsed.title,
      description: parsed.description,
      metadata: parsed.metadata,
      selectedCategory: parsed.selectedCategory,
    };
  } catch (error) {
    console.error("❌ Flashcard extraction failed:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}
